#!/bin/bash
set -euo pipefail

[[ ${debug:-} == true ]] && set -x
if [[ ${1:-} == "" ]] ; then 
  echo "ERROR: please set remote-url as first parameter"
  exit 1
else
  remoteurl=$1
fi

pwd

dir=$(basename $remoteurl | sed -e 's/\.git//g' )
if [ -d $dir ]; then 
  echo "ERROR: $dir already exists"
  exit 1
fi
default_delivery_branch="latest"
delivery_branch=$default_delivery_branch

git init $dir
cd $dir
git remote add origin $remoteurl
git config --local remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
mkdir .gitartifact
touch .gitartifact/config .gitignore .gitattributes
echo "#Add git artifact repo description and instructions here" > README.md
git add .
git commit -m "git-artifact repo $remoteurl init"
git push origin HEAD:refs/heads/master -f

echo "Init delivery branch: $delivery_branch"
git checkout -b $delivery_branch
git branch $delivery_branch --set-upstream-to origin/master

git branch -v

echo "Ready to receive artifacts.. directory: $dir"
