#!/bin/bash
set -euo pipefail

[[ ${debug:-} == true ]] && set -x
if [[ ${1:-} == "" ]] ; then 
  echo "ERROR: please set remote-url as first parameter"
  exit 1
else
  remoteurl=$1
fi

pwd

git clone --single-branch --branch master $remoteurl
cd $(basename $remoteurl )
default_delivery_branch="latest"
delivery_branch=$default_delivery_branch
if [[ -e ./setup.sh ]]; then
   echo "Setup file exists - source it"   
   . ./setup.sh
else
  echo "Setup file (setup.sh) does not exit - skip"
fi

echo "Init delivery branch: $delivery_branch"
git checkout -B $delivery_branch --track origin/master

git branch -v

echo "Ready to receive artifacts.."