#!/bin/bash
set -euo pipefail

[[ ${debug:-} == true ]] && set -x
if [[ ${1:-} == "" ]] ; then 
  echo "ERROR: please set artifact-revision as first parameter"
  exit 1
else
  artifact_revision=$1
fi
current_branch=$(git branch --show-current)

echo "Add the artifacts"
git add .

echo "Commit the artifacts"
git commit -q -m "$artifact_revision"

echo "Tagging the artifacts: $artifact_revision"
git tag -m "$artifact_revision" $artifact_revision
